management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 5555

  #Setting logging levels
logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.thoughtmechanix: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  prefix:  /api
  routes:
    # 수동 경로 매핑  http://localhost:5555/oranization/v1/~~
    organizationservice: /organization/**
